package fr.unice.polytech.isa.dd.entities;

public enum DRONE_STATES {
    AVAILABLE, AWAITING_DELIVER, IN_DELIVERING, AWAITING_LOADING, IN_LOADING, AWAITING_TO_BE_AVAILABLE, AWAITING_REPAIR, BEING_REPAIRED
}